# Generated by Django 4.2.4 on 2023-08-24 08:20

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AntennaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antennatype', models.CharField(max_length=20, unique=True)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.CharField(max_length=100, unique=True)),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contracttype', models.CharField(max_length=20, unique=True)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceRET',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20, unique=True)),
                ('band', models.CharField(max_length=20)),
                ('secid', models.IntegerField()),
                ('portnum', models.IntegerField()),
                ('channelcard', models.CharField(max_length=15)),
                ('antennatype', models.CharField(max_length=15)),
                ('remark', models.CharField(max_length=15)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=10, unique=True)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteBasicinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteid', models.CharField(max_length=15, unique=True)),
                ('sitename', models.CharField(max_length=100)),
                ('lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_at', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.cluster')),
                ('contracttype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.contracttype')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.region')),
            ],
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteconfig', models.CharField(max_length=20, unique=True)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteLSMinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, editable=False, max_length=20)),
                ('siteid', models.CharField(max_length=15, unique=True)),
                ('cellnum', models.IntegerField()),
                ('cellidentity', models.IntegerField()),
                ('pci', models.IntegerField()),
                ('pss', models.IntegerField(editable=False)),
                ('sss', models.IntegerField(editable=False)),
                ('earfcndl', models.IntegerField()),
                ('earfcnul', models.IntegerField()),
                ('freqband', models.IntegerField()),
                ('rsi', models.IntegerField()),
                ('tac', models.IntegerField()),
                ('channelcard', models.CharField(max_length=15)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteRETinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, editable=False, max_length=20)),
                ('siteid', models.CharField(max_length=15, unique=True)),
                ('connectbordtype', models.IntegerField()),
                ('connectboardid', models.IntegerField()),
                ('connectportid', models.IntegerField()),
                ('cascaderrhid', models.IntegerField()),
                ('aldid', models.IntegerField()),
                ('antidsubunitid', models.IntegerField()),
                ('tilt', models.IntegerField()),
                ('refuid', models.CharField(editable=False, max_length=50)),
                ('channelcard', models.CharField(editable=False, max_length=15)),
                ('band', models.CharField(editable=False, max_length=20)),
                ('secid', models.IntegerField(editable=False)),
                ('portnum', models.IntegerField(editable=False)),
                ('antennatype', models.CharField(editable=False, max_length=15)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=30, unique=True)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.region')),
            ],
        ),
        migrations.CreateModel(
            name='SitePhyinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antennaheight', models.IntegerField(blank=True, null=True)),
                ('azimuth', models.IntegerField(blank=True, null=True)),
                ('mtilt', models.IntegerField(blank=True, null=True)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_at', models.DateTimeField(auto_now=True)),
                ('antennatype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.antennatype')),
                ('sitebasicinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.sitebasicinfo')),
            ],
        ),
        migrations.AddField(
            model_name='sitebasicinfo',
            name='siteconfig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.siteconfig'),
        ),
        migrations.AddField(
            model_name='sitebasicinfo',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.state'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.region'),
        ),
    ]
