# Generated by Django 4.2.4 on 2023-08-24 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiapp.region'),
        ),
        migrations.AlterField(
            model_name='sitebasicinfo',
            name='cluster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiapp.cluster'),
        ),
        migrations.AlterField(
            model_name='sitebasicinfo',
            name='contracttype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiapp.contracttype'),
        ),
        migrations.AlterField(
            model_name='sitebasicinfo',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiapp.region'),
        ),
        migrations.AlterField(
            model_name='sitebasicinfo',
            name='siteconfig',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiapp.siteconfig'),
        ),
        migrations.AlterField(
            model_name='sitebasicinfo',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiapp.state'),
        ),
        migrations.AlterField(
            model_name='sitephyinfo',
            name='antennatype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiapp.antennatype'),
        ),
        migrations.AlterField(
            model_name='sitephyinfo',
            name='sitebasicinfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiapp.sitebasicinfo'),
        ),
        migrations.AlterField(
            model_name='state',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiapp.region'),
        ),
    ]
