# Generated by Django 4.2.4 on 2023-08-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_alter_cluster_region_alter_sitebasicinfo_cluster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenceret',
            name='antennatype',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='referenceret',
            name='band',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='referenceret',
            name='channelcard',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='referenceret',
            name='portnum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='referenceret',
            name='remark',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='referenceret',
            name='secid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitelsminfo',
            name='cellidentity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitelsminfo',
            name='cellnum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitelsminfo',
            name='earfcndl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitelsminfo',
            name='earfcnul',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitelsminfo',
            name='freqband',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitelsminfo',
            name='pci',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitelsminfo',
            name='rsi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitelsminfo',
            name='tac',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteretinfo',
            name='aldid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteretinfo',
            name='antidsubunitid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteretinfo',
            name='cascaderrhid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteretinfo',
            name='connectboardid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteretinfo',
            name='connectbordtype',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteretinfo',
            name='connectportid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteretinfo',
            name='tilt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
