# Generated by Django 4.2.4 on 2023-08-25 00:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0003_alter_referenceret_antennatype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FACApproveStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facapprovestatus', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PACApproveStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pacapprovestatus', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField(blank=True, null=True)),
                ('completedate', models.DateField(blank=True, null=True)),
                ('ssvsubmitdate', models.DateField(blank=True, null=True)),
                ('bsreceivedate', models.DateField(blank=True, null=True)),
                ('bssubmitdate', models.DateField(blank=True, null=True)),
                ('bsapprovedate', models.DateField(blank=True, null=True)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_at', models.DateTimeField(auto_now=True)),
                ('sitebasicinfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiapp.sitebasicinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Optimization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField(blank=True, null=True)),
                ('completedate', models.DateField(blank=True, null=True)),
                ('submitdate', models.DateField(blank=True, null=True)),
                ('approvedate', models.DateField(blank=True, null=True)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_at', models.DateTimeField(auto_now=True)),
                ('sitebasicinfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiapp.sitebasicinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Install',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField(blank=True, null=True)),
                ('completedate', models.DateField(blank=True, null=True)),
                ('integrationdate', models.DateField(blank=True, null=True)),
                ('integrationondate', models.DateField(blank=True, null=True)),
                ('oaairdate', models.DateField(blank=True, null=True)),
                ('coisubmitdate', models.DateField(blank=True, null=True)),
                ('coiapprovedate', models.DateField(blank=True, null=True)),
                ('coicsubmitdate', models.DateField(blank=True, null=True)),
                ('coicapprovestatus', models.CharField(blank=True, max_length=20, null=True)),
                ('pnochotriggerdate', models.DateField(blank=True, null=True)),
                ('pnochocompletedate', models.DateField(blank=True, null=True)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_at', models.DateTimeField(auto_now=True)),
                ('sitebasicinfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiapp.sitebasicinfo')),
            ],
        ),
        migrations.CreateModel(
            name='DO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doissuedate', models.DateField(blank=True, null=True)),
                ('codsubmitdate', models.DateField(blank=True, null=True)),
                ('codapprovedate', models.DateField(blank=True, null=True)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_at', models.DateTimeField(auto_now=True)),
                ('sitebasicinfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiapp.sitebasicinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pacsubmitdate', models.DateField(blank=True, null=True)),
                ('facsubmitdate', models.DateField(blank=True, null=True)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_at', models.DateTimeField(auto_now=True)),
                ('facapprovestatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiapp.facapprovestatus')),
                ('pacapprovestatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiapp.pacapprovestatus')),
                ('sitebasicinfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiapp.sitebasicinfo')),
            ],
        ),
    ]
