# Generated by Django 4.2.4 on 2023-08-25 01:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0004_facapprovestatus_pacapprovestatus_ssv_optimization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OPTIssuetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optissuetype', models.CharField(blank=True, max_length=20, null=True)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SSVIssuetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssvissuetype', models.CharField(blank=True, max_length=20, null=True)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcon', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('remark', models.TextField(blank=True, null=True)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SSVIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(blank=True, null=True)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_at', models.DateTimeField(auto_now=True)),
                ('issuetype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiapp.ssvissuetype')),
                ('sitebasicinfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiapp.sitebasicinfo')),
            ],
        ),
        migrations.CreateModel(
            name='OptIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(blank=True, null=True)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_at', models.DateTimeField(auto_now=True)),
                ('issuetype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiapp.optissuetype')),
                ('sitebasicinfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiapp.sitebasicinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dumaterial', models.CharField(choices=[('Samsung-Material', 'Samsung-Material'), ('Reuse-Material', 'Reuse-Material')], max_length=20)),
                ('rumaterial', models.CharField(choices=[('Samsung-Material', 'Samsung-Material'), ('Reuse-Material', 'Reuse-Material')], max_length=20)),
                ('remark', models.TextField(blank=True)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_at', models.DateTimeField(auto_now=True)),
                ('sitebasicinfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiapp.sitebasicinfo')),
            ],
        ),
        migrations.CreateModel(
            name='AllTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_at', models.DateTimeField(auto_now=True)),
                ('certification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiapp.certification')),
                ('do', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiapp.do')),
                ('install', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiapp.install')),
                ('optimization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiapp.optimization')),
                ('sitebasicinfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiapp.sitebasicinfo')),
                ('ssv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiapp.ssv')),
            ],
        ),
    ]
