# Generated by Django 4.2.4 on 2023-08-25 01:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0005_optissuetype_ssvissuetype_subcon_ssvissue_optissue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OPTType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opttype', models.CharField(max_length=20)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
