# Generated by Django 4.2.4 on 2023-08-30 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0007_coicapprovestatus_alter_install_coicapprovestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimization',
            name='opttype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiapp.opttype'),
        ),
    ]
