# Generated by Django 4.2.4 on 2023-09-01 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0008_optimization_opttype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ssv',
            old_name='completedate',
            new_name='ssvcompletedate',
        ),
        migrations.RenameField(
            model_name='ssv',
            old_name='startdate',
            new_name='ssvstartdate',
        ),
    ]
