# Generated by Django 4.2.4 on 2023-09-01 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0009_rename_completedate_ssv_ssvcompletedate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssv',
            name='ssvsubcon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiapp.subcon'),
        ),
    ]
