# Generated by Django 4.2.4 on 2023-09-01 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0010_ssv_ssvsubcon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optimization',
            old_name='approvedate',
            new_name='optapprovedate',
        ),
        migrations.RenameField(
            model_name='optimization',
            old_name='completedate',
            new_name='optcompletedate',
        ),
        migrations.RenameField(
            model_name='optimization',
            old_name='startdate',
            new_name='optstartdate',
        ),
        migrations.RenameField(
            model_name='optimization',
            old_name='submitdate',
            new_name='optsubmitdate',
        ),
    ]
