# Generated by Django 4.2.4 on 2023-09-01 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0011_rename_approvedate_optimization_optapprovedate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimization',
            name='optsubcon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiapp.subcon'),
        ),
    ]
