# Generated by Django 4.2.4 on 2023-09-04 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0012_optimization_optsubcon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitelsminfo',
            name='channelcard',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='sitelsminfo',
            name='siteid',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
