# Generated by Django 4.2.4 on 2023-09-04 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0014_rename_antidsubunitid_siteretinfo_antidsubnetid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitebasicinfo',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='sitebasicinfo',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True),
        ),
    ]
