# Generated by Django 4.2.4 on 2023-09-04 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0016_alter_referenceret_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenceret',
            name='antennatype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='referenceret',
            name='channelcard',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='referenceret',
            name='remark',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
