# Generated by Django 4.2.4 on 2023-09-04 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0017_alter_referenceret_antennatype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteretinfo',
            name='antennatype',
            field=models.CharField(blank=True, editable=False, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='siteretinfo',
            name='band',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='siteretinfo',
            name='channelcard',
            field=models.CharField(blank=True, editable=False, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='siteretinfo',
            name='refuid',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='siteretinfo',
            name='secid',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
