# Generated by Django 4.2.4 on 2023-09-04 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0018_alter_siteretinfo_antennatype_alter_siteretinfo_band_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteretinfo',
            name='portnum',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
