# Generated by Django 4.2.4 on 2023-09-04 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0019_alter_siteretinfo_portnum'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SitePhyinfo',
        ),
    ]
