# Generated by Django 4.2.4 on 2023-09-04 07:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0020_delete_sitephyinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePhyinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secid', models.IntegerField(blank=True, null=True)),
                ('band', models.IntegerField(blank=True, null=True)),
                ('antennaheight', models.IntegerField(blank=True, null=True)),
                ('azimuth', models.IntegerField(blank=True, null=True)),
                ('mtilt', models.IntegerField(blank=True, null=True)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_at', models.DateTimeField(auto_now=True)),
                ('antennatype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiapp.antennatype')),
                ('sitebasicinfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiapp.sitebasicinfo')),
            ],
        ),
    ]
