# Generated by Django 4.2.4 on 2023-09-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0021_sitephyinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitephyinfo',
            name='portnum',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
