# Generated by Django 4.2.4 on 2023-09-04 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0022_sitephyinfo_portnum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coicapprovestatus',
            old_name='coiapprovestatus',
            new_name='coicapprovestatus',
        ),
    ]
