# Generated by Django 4.2.4 on 2023-09-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0023_rename_coiapprovestatus_coicapprovestatus_coicapprovestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitephyinfo',
            name='uid',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
    ]
