# Generated by Django 4.2.4 on 2023-09-07 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0025_alter_alltable_certification_alter_alltable_do_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alltable',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apiapp.material'),
        ),
    ]
