# Generated by Django 4.2.4 on 2023-09-07 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0026_alltable_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitephyinfo',
            name='etitl',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
