# Generated by Django 4.2.4 on 2023-09-07 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0028_rename_etitl_sitephyinfo_etit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitephyinfo',
            old_name='etit',
            new_name='etilt',
        ),
    ]
