# Generated by Django 4.2.4 on 2023-09-15 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0029_rename_etit_sitephyinfo_etilt'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitelsminfo',
            name='sitebasicinfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apiapp.sitebasicinfo'),
        ),
        migrations.AddField(
            model_name='siteretinfo',
            name='sitebasicinfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apiapp.sitebasicinfo'),
        ),
    ]
