# Generated by Django 4.2.4 on 2023-09-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0030_sitelsminfo_sitebasicinfo_siteretinfo_sitebasicinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteretinfo',
            name='antennatype',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='siteretinfo',
            name='refuid',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
