# Generated by Django 4.2.4 on 2023-09-19 06:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0031_alter_siteretinfo_antennatype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fastatus', models.CharField(blank=True, max_length=50, null=True)),
                ('modify_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OptReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewdate', models.DateField(blank=True, null=True)),
                ('fadetail', models.TextField(blank=True, null=True)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_at', models.DateTimeField(auto_now=True)),
                ('fastatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apiapp.fastatus')),
            ],
        ),
        migrations.CreateModel(
            name='PIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.CharField(blank=True, max_length=50, null=True)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apiapp.region')),
            ],
        ),
        migrations.RemoveField(
            model_name='ssvissue',
            name='issuetype',
        ),
        migrations.RemoveField(
            model_name='ssvissue',
            name='sitebasicinfo',
        ),
        migrations.AddField(
            model_name='optimization',
            name='optissuedetail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='optimization',
            name='optissuetype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apiapp.optissuetype'),
        ),
        migrations.AddField(
            model_name='ssv',
            name='ssvissuedetail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ssv',
            name='ssvissuetype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apiapp.ssvissuetype'),
        ),
        migrations.DeleteModel(
            name='OptIssue',
        ),
        migrations.DeleteModel(
            name='SSVIssue',
        ),
        migrations.AddField(
            model_name='optreview',
            name='pic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apiapp.pic'),
        ),
        migrations.AddField(
            model_name='optreview',
            name='sitebasicinfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apiapp.sitebasicinfo'),
        ),
    ]
