# Generated by Django 4.2.4 on 2023-09-20 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0032_fastatus_optreview_pic_remove_ssvissue_issuetype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='dumaterial',
            field=models.CharField(choices=[(None, 'None'), ('Samsung-Material', 'Samsung-Material'), ('Reuse-Material', 'Reuse-Material')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='rumaterial',
            field=models.CharField(choices=[(None, 'None'), ('Samsung-Material', 'Samsung-Material'), ('Reuse-Material', 'Reuse-Material')], max_length=20, null=True),
        ),
    ]
