# Generated by Django 4.2.4 on 2023-09-22 02:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0033_alter_material_dumaterial_alter_material_rumaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fastatus',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
