# Generated by Django 4.2.4 on 2023-09-22 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0035_rename_fastatus_reviewstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewstatus',
            old_name='fastatus',
            new_name='reviewstatus',
        ),
    ]
