# Generated by Django 4.2.4 on 2023-09-22 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0036_rename_fastatus_reviewstatus_reviewstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optreview',
            old_name='fastatus',
            new_name='reviewstatus',
        ),
    ]
