# Generated by Django 4.2.4 on 2023-09-22 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0037_rename_fastatus_optreview_reviewstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optreview',
            old_name='fadetail',
            new_name='reviewdetail',
        ),
    ]
