# Generated by Django 4.2.4 on 2023-09-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0038_rename_fadetail_optreview_reviewdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
