# Generated by Django 4.2.4 on 2023-10-24 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0040_testresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitelsminfo',
            name='sitestatus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
