# Generated by Django 4.2.4 on 2023-10-25 03:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0041_sitelsminfo_sitestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteTXattninfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, editable=False, max_length=20)),
                ('siteid', models.CharField(blank=True, editable=False, max_length=15)),
                ('connectboardid', models.IntegerField(blank=True, null=True)),
                ('connectportid', models.IntegerField(blank=True, null=True)),
                ('txattn', models.IntegerField(blank=True, null=True)),
                ('cellnum', models.IntegerField(blank=True, null=True)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_at', models.DateTimeField(auto_now=True)),
                ('sitebasicinfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apiapp.sitebasicinfo')),
            ],
        ),
    ]
