# Generated by Django 4.2.4 on 2023-10-25 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0042_sitetxattninfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetxattninfo',
            name='sitestatus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
