# Generated by Django 4.2.4 on 2023-10-30 08:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0043_sitetxattninfo_sitestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.CharField(blank=True, max_length=100, null=True)),
                ('sysid', models.CharField(blank=True, max_length=50, null=True)),
                ('cellnul', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('weeknum', models.CharField(blank=True, max_length=50, null=True)),
                ('uid', models.CharField(blank=True, max_length=100, null=True)),
                ('Cell_Availability', models.FloatField(blank=True, null=True)),
                ('Attach_Setup_Success_Rate', models.FloatField(blank=True, null=True)),
                ('RRC_Setup_Success_Rate', models.FloatField(blank=True, null=True)),
                ('eRAB_Setup_Success_Rate_nGBR', models.FloatField(blank=True, null=True)),
                ('VoLTE_Setup_Success_Rate_GBR', models.FloatField(blank=True, null=True)),
                ('Call_Drop_Rate_eRAB_nGBR', models.FloatField(blank=True, null=True)),
                ('VoLTE_Call_Drop_Rate_eRAB_GBR', models.FloatField(blank=True, null=True)),
                ('HOSR_Intra_Frequency', models.FloatField(blank=True, null=True)),
                ('HOSR_Inter_Frequency', models.FloatField(blank=True, null=True)),
                ('X2_Handover_Out_Success_Rate', models.FloatField(blank=True, null=True)),
                ('X2_Handover_In_Success_Rate', models.FloatField(blank=True, null=True)),
                ('S1_Handover_Out_Success_Rate', models.FloatField(blank=True, null=True)),
                ('S1_Handover_In_Success_Rate', models.FloatField(blank=True, null=True)),
                ('DL_BLER', models.FloatField(blank=True, null=True)),
                ('UL_BLER', models.FloatField(blank=True, null=True)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_at', models.DateTimeField(auto_now=True)),
                ('regrion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apiapp.region')),
                ('sitebasicinfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apiapp.sitebasicinfo')),
                ('sitephyinfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apiapp.sitephyinfo')),
            ],
        ),
    ]
