# Generated by Django 4.2.4 on 2023-10-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0045_statistic_band'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='sitestatus',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
