# Generated by Django 4.2.4 on 2023-10-30 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0046_statistic_sitestatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistic',
            old_name='cellnul',
            new_name='cellnum',
        ),
    ]
