# Generated by Django 4.2.4 on 2023-10-30 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0047_rename_cellnul_statistic_cellnum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistic',
            old_name='Attach_Setup_Success_Rate',
            new_name='attach_setup_success_rate',
        ),
        migrations.RenameField(
            model_name='statistic',
            old_name='Call_Drop_Rate_eRAB_nGBR',
            new_name='call_drop_rate_erab_ngbr',
        ),
        migrations.RenameField(
            model_name='statistic',
            old_name='Cell_Availability',
            new_name='cell_availability',
        ),
        migrations.RenameField(
            model_name='statistic',
            old_name='DL_BLER',
            new_name='dl_bler',
        ),
        migrations.RenameField(
            model_name='statistic',
            old_name='HOSR_Inter_Frequency',
            new_name='erab_setup_success_rate_ngbr',
        ),
        migrations.RenameField(
            model_name='statistic',
            old_name='HOSR_Intra_Frequency',
            new_name='hosr_inter_frequency',
        ),
        migrations.RenameField(
            model_name='statistic',
            old_name='RRC_Setup_Success_Rate',
            new_name='hosr_intra_frequency',
        ),
        migrations.RenameField(
            model_name='statistic',
            old_name='regrion',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='statistic',
            old_name='S1_Handover_In_Success_Rate',
            new_name='rrd_setup_success_rate',
        ),
        migrations.RenameField(
            model_name='statistic',
            old_name='S1_Handover_Out_Success_Rate',
            new_name='s1_handover_in_success_rate',
        ),
        migrations.RenameField(
            model_name='statistic',
            old_name='UL_BLER',
            new_name='s1_handover_out_success_rate',
        ),
        migrations.RenameField(
            model_name='statistic',
            old_name='VoLTE_Call_Drop_Rate_eRAB_GBR',
            new_name='ul_bler',
        ),
        migrations.RenameField(
            model_name='statistic',
            old_name='VoLTE_Setup_Success_Rate_GBR',
            new_name='volte_call_drop_rate_erab_gbr',
        ),
        migrations.RenameField(
            model_name='statistic',
            old_name='X2_Handover_In_Success_Rate',
            new_name='volte_setup_success_rate_gbr',
        ),
        migrations.RenameField(
            model_name='statistic',
            old_name='X2_Handover_Out_Success_Rate',
            new_name='x2_handover_in_success_rate',
        ),
        migrations.RenameField(
            model_name='statistic',
            old_name='eRAB_Setup_Success_Rate_nGBR',
            new_name='x2_handover_out_success_rate',
        ),
    ]
