# Generated by Django 4.2.4 on 2023-10-30 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0048_rename_attach_setup_success_rate_statistic_attach_setup_success_rate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistic',
            old_name='rrd_setup_success_rate',
            new_name='rrc_setup_success_rate',
        ),
    ]
