# Generated by Django 4.2.4 on 2023-11-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0050_statisticdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statisticdata',
            old_name='eccbdspauditrlcmaccallrelease_qci59',
            new_name='calldropqci_eccbdspauditrlcmaccallrelease_qci59',
        ),
        migrations.AlterField(
            model_name='statisticdata',
            name='dltransmissionretrans0_600',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statisticdata',
            name='ultransmissionretrans0_600',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
