# Generated by Django 4.2.4 on 2023-11-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0052_statisticcalculated'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticcalculated',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
