# Generated by Django 4.2.4 on 2023-11-17 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0053_statisticcalculated_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statisticcalculated',
            old_name='cell_availabilityy',
            new_name='cell_availability',
        ),
    ]
