# Generated by Django 4.2.4 on 2023-11-17 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0054_rename_cell_availabilityy_statisticcalculated_cell_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticcalculated',
            name='uid',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
    ]
