# Generated by Django 4.2.4 on 2023-11-17 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0055_statisticcalculated_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticcalculated',
            name='uid',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
    ]
