# Generated by Django 4.2.4 on 2023-12-28 07:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0057_alter_statisticcalculated_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticCalculatedCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.CharField(blank=True, max_length=100, null=True)),
                ('band', models.CharField(blank=True, max_length=100, null=True)),
                ('weeknum', models.CharField(blank=True, max_length=50, null=True)),
                ('cell_availability', models.FloatField(blank=True, null=True)),
                ('attach_setup_success_rate', models.FloatField(blank=True, null=True)),
                ('rrc_setup_success_rate', models.FloatField(blank=True, null=True)),
                ('erab_setup_success_rate_ngbr', models.FloatField(blank=True, null=True)),
                ('volte_setup_success_rate_gbr', models.FloatField(blank=True, null=True)),
                ('call_drop_rate_erab_ngbr', models.FloatField(blank=True, null=True)),
                ('volte_call_drop_rate_erab_gbr', models.FloatField(blank=True, null=True)),
                ('hosr_intra_frequency', models.FloatField(blank=True, null=True)),
                ('hosr_inter_frequency', models.FloatField(blank=True, null=True)),
                ('x2_handover_out_success_rate', models.FloatField(blank=True, null=True)),
                ('x2_handover_in_success_rate', models.FloatField(blank=True, null=True)),
                ('s1_handover_out_success_rate', models.FloatField(blank=True, null=True)),
                ('s1_handover_in_success_rate', models.FloatField(blank=True, null=True)),
                ('dl_bler', models.FloatField(blank=True, null=True)),
                ('ul_bler', models.FloatField(blank=True, null=True)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apiapp.region')),
            ],
        ),
    ]
