# Generated by Django 4.2.4 on 2023-12-29 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apiapp', '0058_statisticcalculatedcluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitephyinfo',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='statisticcalculatedcluster',
            name='uid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
