# Generated by Django 4.2.4 on 2024-01-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0059_sitephyinfo_modified_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitephyinfo',
            name='modified_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
