# Generated by Django 4.2.4 on 2024-06-26 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0060_alter_sitephyinfo_modified_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=100, null=True)),
                ('folder', models.CharField(blank=True, max_length=100, null=True)),
                ('alarm', models.TextField(blank=True, null=True)),
                ('material_remark', models.CharField(blank=True, max_length=100, null=True)),
                ('sitebasicinfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apiapp.sitebasicinfo')),
            ],
        ),
    ]
