# Generated by Django 4.2.4 on 2024-06-27 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0062_alarmdata_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmdata',
            name='alarmdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
